/*eslint-disable max-len*/

// note: all routes on reddit:
// (how to generate this
// - find RouterComponent in the react components list
// - right click, store as global variable
/*
copy(
     JSON.stringify([...new Set($reactTemp0
        .map(route => ({
            path: Array.isArray(route.props.path) ? route.props.path : [route.props.path],
            exact: !!route.props.exact,
        }))
        .flatMap(itm => itm.path.map(pth => (itm.exact ? "" : "inexact|")+pth))
        .sort()
        .flatMap(itm => {
            const matches = itm.matchAll(/\/:[a-zA-Z]+?\(([a-zA-Z\|]+)\)(\??)/g);

            let allitms = [itm];

            for(const [wholematch, group, isq] of matches) {
                const msplit = group.split("|");
                if(allitms.length === 1 || (msplit.length === 1 && isq === "")) {
                    const aitm = allitms[0];
                    allitms = [];
                    if(isq === "?") allitms.push(aitm.replace(wholematch, ""));
                    for(const pick of msplit) {
                        allitms.push(aitm.replace(wholematch, "/"+pick));
                    }
                }
            }

            return allitms;
        })
     )], null, "    ")
   )
*/
// how to test routes without reloading:
// {
//   const teststate = (state) => {
//     history.pushState({}, "Hi", state);
//     history.pushState({}, "Hi", state);
//     history.back(); 
//   }
//   teststate("/route")
// }

export const all_builtin_newreddit_routes = new Set([
    "/",
    "",
    // [snipped out a section of /:languageCode/]
    // seems like new.reddit is adding languageCode and countryCode into the url but for some reason they
    // couldn't do that as a preprocessing step beefore the url parsing?
    // anyway they seem to all be redirects for now so it doesn't matter for us
    "/best",
    "/hot",
    "/new",
    "/rising",
    "/controversial",
    "/top",
    "/gilded",
    "/awarded",
    "/acknowledgements",
    "/appeal",
    "/appeals",
    "/avatar",
    "/avatar/:username",
    "/avatar/:username/:avatarId",
    "/coins",
    "/coins/mobile",
    "/comments/:partialPostId/:urlSafePostTitle/:partialCommentId",
    "/comments/:partialPostId/:urlSafePostTitle?",
    "/community-points/",
    "/community-points/documentation/*",
    "/duplicates/:partialPostId/:urlSafePostTitle?",
    "/econ-management",
    "/explore",
    "/explore/:categoryName",
    "/framedGild/:thingId",
    "/framedModal/:type",
    "/label/subreddits",
    "/me/f/mod",
    "/me/f/mod/awarded",
    "/me/f/mod/best",
    "/me/f/mod/controversial",
    "/me/f/mod/gilded",
    "/me/f/mod/hot",
    "/me/f/mod/new",
    "/me/f/mod/rising",
    "/me/f/mod/top",
    "/me/m/:multiredditName",
    "/me/m/:multiredditName/awarded",
    "/me/m/:multiredditName/best",
    "/me/m/:multiredditName/controversial",
    "/me/m/:multiredditName/gilded",
    "/me/m/:multiredditName/hot",
    "/me/m/:multiredditName/new",
    "/me/m/:multiredditName/rising",
    "/me/m/:multiredditName/top",
    "/me/m/:multiredditName/search",
    "/message/inbox",
    "/message/unread",
    "/message/messages",
    "/message/comments",
    "/message/selfreply",
    "/message/mentions",
    "/message/compose",
    "/message/sent",
    "/message/moderator",
    "/message/messages/:messageId([A-Za-z0-9]+)",
    "/notifications/",
    "/original",
    "/original/:categoryName/:sort([a-z]+)?",
    "/original/submit",
    "/powerup",
    "/powerups",
    "/prediction",
    "/predictions",
    "/premium",
    "/r/:subredditName",
    "/r/:subredditName/awarded",
    "/r/:subredditName/best",
    "/r/:subredditName/controversial",
    "/r/:subredditName/gilded",
    "/r/:subredditName/hot",
    "/r/:subredditName/new",
    "/r/:subredditName/rising",
    "/r/:subredditName/top",
    "/r/:subredditName/about",
    "/r/:subredditName/about/awards",
    "/r/:subredditName/about/powerups",
    "/r/:subredditName/about/muted",
    "/r/:subredditName/about/badges",
    "/r/:subredditName/about/banned",
    "/r/:subredditName/about/chat",
    "/r/:subredditName/about/settings",
    "/r/:subredditName/about/contributors",
    "/r/:subredditName/about/emojis",
    "/r/:subredditName/about/emotes",
    "/r/:subredditName/about/eventposts",
    "/r/:subredditName/about/moderators",
    "/r/:subredditName/about/rules",
    "/r/:subredditName/about/removal",
    "/r/:subredditName/about/modqueue",
    "/r/:subredditName/about/reports",
    "/r/:subredditName/about/spam",
    "/r/:subredditName/about/talkhosts",
    "/r/:subredditName/about/unmoderated",
    "/r/:subredditName/about/edited",
    "/r/:subredditName/about/postflair",
    "/r/:subredditName/about/log",
    "/r/:subredditName/about/flair",
    "/r/:subredditName/about/edit",
    "/r/:subredditName/about/userflair",
    "/r/:subredditName/about/wiki",
    "/r/:subredditName/about/wikicontributors",
    "/r/:subredditName/about/wikibanned",
    "/r/:subredditName/about/traffic",
    "/r/:subredditName/about/scheduledposts",
    "/r/:subredditName/about/broadcasting",
    "/r/:subredditName/about/content",
    "/r/:subredditName/about/predictions",
    "/r/:subredditName/about/wiki/:wikiPageName*",
    "/r/:subredditName/about/wiki/edit/:wikiPageName+",
    "/r/:subredditName/about/wiki/create/:wikiPageName+",
    "/r/:subredditName/about/wiki/settings/:wikiPageName+",
    "/r/:subredditName/about/wiki/revisions/:wikiPageName+",
    "/r/:subredditName/about/wiki/revisions",
    "/r/:subredditName/about/wiki/wikibanned",
    "/r/:subredditName/about/wiki/wikicontributors",
    "/r/:subredditName/predictions",
    "/r/:subredditName/search",
    "/r/:subredditName/submit",
    "/r/:subredditName/w/:wikiPageName*",
    "/r/:subredditName/wiki/",
    "/r/:subredditName/wiki/:wikiPageName+",
    "/r/:subredditName/wiki/edit/:wikiPageName+",
    "/r/:subredditName/wiki/create/:wikiPageName+",
    "/r/:subredditName/wiki/revisions/:wikiPageName+",
    "/r/:subredditName/wiki/revisions",
    "/r/:subredditName/wiki/settings/:wikiPageName+",
    "/r/mod",
    "/r/mod/awarded",
    "/r/mod/best",
    "/r/mod/controversial",
    "/r/mod/gilded",
    "/r/mod/hot",
    "/r/mod/new",
    "/r/mod/rising",
    "/r/mod/top",
    "/r/mod/about",
    "/r/mod/about/edited",
    "/r/mod/about/modqueue",
    "/r/mod/about/reports",
    "/r/mod/about/spam",
    "/r/mod/about/unmoderated",
    "/r/u_:profileName",
    "/r/u_:profileName/:rest(.*)",
    "/report",
    "/rpan/:partialPostId?",
    "/rpan/r/:subredditName/:partialPostId?",
    "/search",
    "/settings",
    "/settings/account",
    "/settings/messaging",
    "/settings/profile",
    "/settings/privacy",
    "/settings/notifications",
    "/settings/feed",
    "/settings/gold",
    "/settings/payments",
    "/settings/premium",
    "/settings/creator",
    "/settings/special",
    "/settings/dsp",
    "/settings/data-request",
    "/submit",
    "/subreddits/leaderboard",
    "/subreddits/leaderboard/:categoryName/",
    "/t/:topicSlug",
    "/talk",
    "/u/:profileName",
    "/u/:profileName/:rest(.*)",
    "/u/me/avatar",
    "/user/:profileName",
    "/user/:profileName/downvoted",
    "/user/:profileName/hidden",
    "/user/:profileName/saved",
    "/user/:profileName/upvoted",
    "/user/:profileName/gilded",
    "/user/:profileName/given",
    "/user/:profileName/about/awards",
    "/user/:profileName/about/edit/moderation",
    "/user/:profileName/avatar",
    "/user/:profileName/comments",
    "/user/:profileName/draft/:draftId",
    "/user/:profileName/followers",
    "/user/:profileName/gilded/given",
    "/user/:profileName/posts",
    "/user/:profileName/snoo",
    "/user/:profileName/submit",
    "/user/:profileName/submitted",
    "/user/:profileName/submitted/:rest(.*)",
    "/user/:username/m/:multiredditName",
    "/user/:username/m/:multiredditName/awarded",
    "/user/:username/m/:multiredditName/best",
    "/user/:username/m/:multiredditName/controversial",
    "/user/:username/m/:multiredditName/gilded",
    "/user/:username/m/:multiredditName/hot",
    "/user/:username/m/:multiredditName/new",
    "/user/:username/m/:multiredditName/rising",
    "/user/:username/m/:multiredditName/top",
    "/user/:username/m/:multiredditName/search",
    "/user/me",
    "/user/me/:rest(.*)",
    "/user/me/avatar",
    "/vault/",
    "/vault/burn",
    "/verification/:verificationToken",
    "/w/:wikiPageName*",
    "/web/community-points/",
    "/web/membership/:subredditName",
    "/web/points-migration/",
    "/web/special-membership/:subredditName",
    "/wiki/",
    "/wiki/:wikiPageName+",
    "inexact|/prefs",
    "inexact|/prefs/deactivate",
    "inexact|/prefs/blocked",
    "inexact|/user/:username/about/edit",
    "inexact|/user/:username/about/edit/privacy",
]);