import {refractor} from "refractor/lib/core";

import i0 from "refractor/lang/clike.js";
refractor.register(i0);
import i1 from "refractor/lang/c.js";
refractor.register(i1);
import i2 from "refractor/lang/cpp.js";
refractor.register(i2);
import i3 from "refractor/lang/arduino.js";
refractor.register(i3);
import i4 from "refractor/lang/bash.js";
refractor.register(i4);
import i5 from "refractor/lang/csharp.js";
refractor.register(i5);
import i6 from "refractor/lang/markup.js";
refractor.register(i6);
import i7 from "refractor/lang/css.js";
refractor.register(i7);
import i8 from "refractor/lang/diff.js";
refractor.register(i8);
import i9 from "refractor/lang/go.js";
refractor.register(i9);
import i10 from "refractor/lang/ini.js";
refractor.register(i10);
import i11 from "refractor/lang/java.js";
refractor.register(i11);
import i12 from "refractor/lang/regex.js";
refractor.register(i12);
import i13 from "refractor/lang/javascript.js";
refractor.register(i13);
import i14 from "refractor/lang/json.js";
refractor.register(i14);
import i15 from "refractor/lang/kotlin.js";
refractor.register(i15);
import i16 from "refractor/lang/less.js";
refractor.register(i16);
import i17 from "refractor/lang/lua.js";
refractor.register(i17);
import i18 from "refractor/lang/makefile.js";
refractor.register(i18);
import i19 from "refractor/lang/yaml.js";
refractor.register(i19);
import i20 from "refractor/lang/markdown.js";
refractor.register(i20);
import i21 from "refractor/lang/objectivec.js";
refractor.register(i21);
import i22 from "refractor/lang/perl.js";
refractor.register(i22);
import i23 from "refractor/lang/markup-templating.js";
refractor.register(i23);
import i24 from "refractor/lang/php.js";
refractor.register(i24);
import i25 from "refractor/lang/python.js";
refractor.register(i25);
import i26 from "refractor/lang/r.js";
refractor.register(i26);
import i27 from "refractor/lang/ruby.js";
refractor.register(i27);
import i28 from "refractor/lang/rust.js";
refractor.register(i28);
import i29 from "refractor/lang/sass.js";
refractor.register(i29);
import i30 from "refractor/lang/scss.js";
refractor.register(i30);
import i31 from "refractor/lang/sql.js";
refractor.register(i31);
import i32 from "refractor/lang/swift.js";
refractor.register(i32);
import i33 from "refractor/lang/typescript.js";
refractor.register(i33);
import i34 from "refractor/lang/basic.js";
refractor.register(i34);
import i35 from "refractor/lang/vbnet.js";
refractor.register(i35);