import {refractor} from "refractor/lib/core";

import i0 from "refractor/lang/abap.js";
refractor.register(i0);
import i1 from "refractor/lang/abnf.js";
refractor.register(i1);
import i2 from "refractor/lang/actionscript.js";
refractor.register(i2);
import i3 from "refractor/lang/ada.js";
refractor.register(i3);
import i4 from "refractor/lang/agda.js";
refractor.register(i4);
import i5 from "refractor/lang/al.js";
refractor.register(i5);
import i6 from "refractor/lang/antlr4.js";
refractor.register(i6);
import i7 from "refractor/lang/apacheconf.js";
refractor.register(i7);
import i8 from "refractor/lang/apex.js";
refractor.register(i8);
import i9 from "refractor/lang/apl.js";
refractor.register(i9);
import i10 from "refractor/lang/applescript.js";
refractor.register(i10);
import i11 from "refractor/lang/aql.js";
refractor.register(i11);
import i12 from "refractor/lang/arff.js";
refractor.register(i12);
import i13 from "refractor/lang/asciidoc.js";
refractor.register(i13);
import i14 from "refractor/lang/aspnet.js";
refractor.register(i14);
import i15 from "refractor/lang/asm6502.js";
refractor.register(i15);
import i16 from "refractor/lang/autohotkey.js";
refractor.register(i16);
import i17 from "refractor/lang/autoit.js";
refractor.register(i17);
import i18 from "refractor/lang/batch.js";
refractor.register(i18);
import i19 from "refractor/lang/bbcode.js";
refractor.register(i19);
import i20 from "refractor/lang/birb.js";
refractor.register(i20);
import i21 from "refractor/lang/bison.js";
refractor.register(i21);
import i22 from "refractor/lang/bnf.js";
refractor.register(i22);
import i23 from "refractor/lang/brainfuck.js";
refractor.register(i23);
import i24 from "refractor/lang/brightscript.js";
refractor.register(i24);
import i25 from "refractor/lang/bro.js";
refractor.register(i25);
import i26 from "refractor/lang/bsl.js";
refractor.register(i26);
import i27 from "refractor/lang/cfscript.js";
refractor.register(i27);
import i28 from "refractor/lang/chaiscript.js";
refractor.register(i28);
import i29 from "refractor/lang/cil.js";
refractor.register(i29);
import i30 from "refractor/lang/clojure.js";
refractor.register(i30);
import i31 from "refractor/lang/cmake.js";
refractor.register(i31);
import i32 from "refractor/lang/cobol.js";
refractor.register(i32);
import i33 from "refractor/lang/coffeescript.js";
refractor.register(i33);
import i34 from "refractor/lang/concurnas.js";
refractor.register(i34);
import i35 from "refractor/lang/csp.js";
refractor.register(i35);
import i36 from "refractor/lang/coq.js";
refractor.register(i36);
import i37 from "refractor/lang/crystal.js";
refractor.register(i37);
import i38 from "refractor/lang/css-extras.js";
refractor.register(i38);
import i39 from "refractor/lang/csv.js";
refractor.register(i39);
import i40 from "refractor/lang/cypher.js";
refractor.register(i40);
import i41 from "refractor/lang/d.js";
refractor.register(i41);
import i42 from "refractor/lang/dart.js";
refractor.register(i42);
import i43 from "refractor/lang/dataweave.js";
refractor.register(i43);
import i44 from "refractor/lang/dax.js";
refractor.register(i44);
import i45 from "refractor/lang/dhall.js";
refractor.register(i45);
import i46 from "refractor/lang/django.js";
refractor.register(i46);
import i47 from "refractor/lang/dns-zone-file.js";
refractor.register(i47);
import i48 from "refractor/lang/docker.js";
refractor.register(i48);
import i49 from "refractor/lang/dot.js";
refractor.register(i49);
import i50 from "refractor/lang/ebnf.js";
refractor.register(i50);
import i51 from "refractor/lang/editorconfig.js";
refractor.register(i51);
import i52 from "refractor/lang/eiffel.js";
refractor.register(i52);
import i53 from "refractor/lang/ejs.js";
refractor.register(i53);
import i54 from "refractor/lang/elixir.js";
refractor.register(i54);
import i55 from "refractor/lang/elm.js";
refractor.register(i55);
import i56 from "refractor/lang/etlua.js";
refractor.register(i56);
import i57 from "refractor/lang/erb.js";
refractor.register(i57);
import i58 from "refractor/lang/erlang.js";
refractor.register(i58);
import i59 from "refractor/lang/excel-formula.js";
refractor.register(i59);
import i60 from "refractor/lang/fsharp.js";
refractor.register(i60);
import i61 from "refractor/lang/factor.js";
refractor.register(i61);
import i62 from "refractor/lang/false.js";
refractor.register(i62);
import i63 from "refractor/lang/firestore-security-rules.js";
refractor.register(i63);
import i64 from "refractor/lang/flow.js";
refractor.register(i64);
import i65 from "refractor/lang/fortran.js";
refractor.register(i65);
import i66 from "refractor/lang/ftl.js";
refractor.register(i66);
import i67 from "refractor/lang/gml.js";
refractor.register(i67);
import i68 from "refractor/lang/gcode.js";
refractor.register(i68);
import i69 from "refractor/lang/gdscript.js";
refractor.register(i69);
import i70 from "refractor/lang/gedcom.js";
refractor.register(i70);
import i71 from "refractor/lang/gherkin.js";
refractor.register(i71);
import i72 from "refractor/lang/git.js";
refractor.register(i72);
import i73 from "refractor/lang/glsl.js";
refractor.register(i73);
import i74 from "refractor/lang/graphql.js";
refractor.register(i74);
import i75 from "refractor/lang/groovy.js";
refractor.register(i75);
import i76 from "refractor/lang/textile.js";
refractor.register(i76);
import i77 from "refractor/lang/haml.js";
refractor.register(i77);
import i78 from "refractor/lang/handlebars.js";
refractor.register(i78);
import i79 from "refractor/lang/haskell.js";
refractor.register(i79);
import i80 from "refractor/lang/haxe.js";
refractor.register(i80);
import i81 from "refractor/lang/hcl.js";
refractor.register(i81);
import i82 from "refractor/lang/hlsl.js";
refractor.register(i82);
import i83 from "refractor/lang/uri.js";
refractor.register(i83);
import i84 from "refractor/lang/http.js";
refractor.register(i84);
import i85 from "refractor/lang/hpkp.js";
refractor.register(i85);
import i86 from "refractor/lang/hsts.js";
refractor.register(i86);
import i87 from "refractor/lang/ichigojam.js";
refractor.register(i87);
import i88 from "refractor/lang/icon.js";
refractor.register(i88);
import i89 from "refractor/lang/icu-message-format.js";
refractor.register(i89);
import i90 from "refractor/lang/idris.js";
refractor.register(i90);
import i91 from "refractor/lang/ignore.js";
refractor.register(i91);
import i92 from "refractor/lang/inform7.js";
refractor.register(i92);
import i93 from "refractor/lang/io.js";
refractor.register(i93);
import i94 from "refractor/lang/j.js";
refractor.register(i94);
import i95 from "refractor/lang/javadoclike.js";
refractor.register(i95);
import i96 from "refractor/lang/scala.js";
refractor.register(i96);
import i97 from "refractor/lang/javadoc.js";
refractor.register(i97);
import i98 from "refractor/lang/javastacktrace.js";
refractor.register(i98);
import i99 from "refractor/lang/jexl.js";
refractor.register(i99);
import i100 from "refractor/lang/jolie.js";
refractor.register(i100);
import i101 from "refractor/lang/jq.js";
refractor.register(i101);
import i102 from "refractor/lang/js-templates.js";
refractor.register(i102);
import i103 from "refractor/lang/jsdoc.js";
refractor.register(i103);
import i104 from "refractor/lang/n4js.js";
refractor.register(i104);
import i105 from "refractor/lang/js-extras.js";
refractor.register(i105);
import i106 from "refractor/lang/json5.js";
refractor.register(i106);
import i107 from "refractor/lang/jsonp.js";
refractor.register(i107);
import i108 from "refractor/lang/jsstacktrace.js";
refractor.register(i108);
import i109 from "refractor/lang/julia.js";
refractor.register(i109);
import i110 from "refractor/lang/keyman.js";
refractor.register(i110);
import i111 from "refractor/lang/kumir.js";
refractor.register(i111);
import i112 from "refractor/lang/latex.js";
refractor.register(i112);
import i113 from "refractor/lang/latte.js";
refractor.register(i113);
import i114 from "refractor/lang/scheme.js";
refractor.register(i114);
import i115 from "refractor/lang/lilypond.js";
refractor.register(i115);
import i116 from "refractor/lang/liquid.js";
refractor.register(i116);
import i117 from "refractor/lang/lisp.js";
refractor.register(i117);
import i118 from "refractor/lang/livescript.js";
refractor.register(i118);
import i119 from "refractor/lang/llvm.js";
refractor.register(i119);
import i120 from "refractor/lang/log.js";
refractor.register(i120);
import i121 from "refractor/lang/lolcode.js";
refractor.register(i121);
import i122 from "refractor/lang/matlab.js";
refractor.register(i122);
import i123 from "refractor/lang/mel.js";
refractor.register(i123);
import i124 from "refractor/lang/mizar.js";
refractor.register(i124);
import i125 from "refractor/lang/mongodb.js";
refractor.register(i125);
import i126 from "refractor/lang/monkey.js";
refractor.register(i126);
import i127 from "refractor/lang/moonscript.js";
refractor.register(i127);
import i128 from "refractor/lang/n1ql.js";
refractor.register(i128);
import i129 from "refractor/lang/nand2tetris-hdl.js";
refractor.register(i129);
import i130 from "refractor/lang/naniscript.js";
refractor.register(i130);
import i131 from "refractor/lang/nasm.js";
refractor.register(i131);
import i132 from "refractor/lang/neon.js";
refractor.register(i132);
import i133 from "refractor/lang/nevod.js";
refractor.register(i133);
import i134 from "refractor/lang/nginx.js";
refractor.register(i134);
import i135 from "refractor/lang/nim.js";
refractor.register(i135);
import i136 from "refractor/lang/nix.js";
refractor.register(i136);
import i137 from "refractor/lang/nsis.js";
refractor.register(i137);
import i138 from "refractor/lang/ocaml.js";
refractor.register(i138);
import i139 from "refractor/lang/opencl.js";
refractor.register(i139);
import i140 from "refractor/lang/openqasm.js";
refractor.register(i140);
import i141 from "refractor/lang/oz.js";
refractor.register(i141);
import i142 from "refractor/lang/parigp.js";
refractor.register(i142);
import i143 from "refractor/lang/parser.js";
refractor.register(i143);
import i144 from "refractor/lang/pascal.js";
refractor.register(i144);
import i145 from "refractor/lang/pascaligo.js";
refractor.register(i145);
import i146 from "refractor/lang/psl.js";
refractor.register(i146);
import i147 from "refractor/lang/pcaxis.js";
refractor.register(i147);
import i148 from "refractor/lang/peoplecode.js";
refractor.register(i148);
import i149 from "refractor/lang/phpdoc.js";
refractor.register(i149);
import i150 from "refractor/lang/php-extras.js";
refractor.register(i150);
import i151 from "refractor/lang/plsql.js";
refractor.register(i151);
import i152 from "refractor/lang/powerquery.js";
refractor.register(i152);
import i153 from "refractor/lang/powershell.js";
refractor.register(i153);
import i154 from "refractor/lang/processing.js";
refractor.register(i154);
import i155 from "refractor/lang/prolog.js";
refractor.register(i155);
import i156 from "refractor/lang/promql.js";
refractor.register(i156);
import i157 from "refractor/lang/properties.js";
refractor.register(i157);
import i158 from "refractor/lang/protobuf.js";
refractor.register(i158);
import i159 from "refractor/lang/stylus.js";
refractor.register(i159);
import i160 from "refractor/lang/twig.js";
refractor.register(i160);
import i161 from "refractor/lang/pug.js";
refractor.register(i161);
import i162 from "refractor/lang/puppet.js";
refractor.register(i162);
import i163 from "refractor/lang/pure.js";
refractor.register(i163);
import i164 from "refractor/lang/purebasic.js";
refractor.register(i164);
import i165 from "refractor/lang/purescript.js";
refractor.register(i165);
import i166 from "refractor/lang/qsharp.js";
refractor.register(i166);
import i167 from "refractor/lang/q.js";
refractor.register(i167);
import i168 from "refractor/lang/qml.js";
refractor.register(i168);
import i169 from "refractor/lang/qore.js";
refractor.register(i169);
import i170 from "refractor/lang/racket.js";
refractor.register(i170);
import i171 from "refractor/lang/jsx.js";
refractor.register(i171);
import i172 from "refractor/lang/tsx.js";
refractor.register(i172);
import i173 from "refractor/lang/reason.js";
refractor.register(i173);
import i174 from "refractor/lang/rego.js";
refractor.register(i174);
import i175 from "refractor/lang/renpy.js";
refractor.register(i175);
import i176 from "refractor/lang/rest.js";
refractor.register(i176);
import i177 from "refractor/lang/rip.js";
refractor.register(i177);
import i178 from "refractor/lang/roboconf.js";
refractor.register(i178);
import i179 from "refractor/lang/robotframework.js";
refractor.register(i179);
import i180 from "refractor/lang/sas.js";
refractor.register(i180);
import i181 from "refractor/lang/shell-session.js";
refractor.register(i181);
import i182 from "refractor/lang/smali.js";
refractor.register(i182);
import i183 from "refractor/lang/smalltalk.js";
refractor.register(i183);
import i184 from "refractor/lang/smarty.js";
refractor.register(i184);
import i185 from "refractor/lang/sml.js";
refractor.register(i185);
import i186 from "refractor/lang/solidity.js";
refractor.register(i186);
import i187 from "refractor/lang/solution-file.js";
refractor.register(i187);
import i188 from "refractor/lang/soy.js";
refractor.register(i188);
import i189 from "refractor/lang/turtle.js";
refractor.register(i189);
import i190 from "refractor/lang/sparql.js";
refractor.register(i190);
import i191 from "refractor/lang/splunk-spl.js";
refractor.register(i191);
import i192 from "refractor/lang/sqf.js";
refractor.register(i192);
import i193 from "refractor/lang/squirrel.js";
refractor.register(i193);
import i194 from "refractor/lang/stan.js";
refractor.register(i194);
import i195 from "refractor/lang/iecst.js";
refractor.register(i195);
import i196 from "refractor/lang/t4-templating.js";
refractor.register(i196);
import i197 from "refractor/lang/t4-cs.js";
refractor.register(i197);
import i198 from "refractor/lang/t4-vb.js";
refractor.register(i198);
import i199 from "refractor/lang/tap.js";
refractor.register(i199);
import i200 from "refractor/lang/tcl.js";
refractor.register(i200);
import i201 from "refractor/lang/tt2.js";
refractor.register(i201);
import i202 from "refractor/lang/toml.js";
refractor.register(i202);
import i203 from "refractor/lang/typoscript.js";
refractor.register(i203);
import i204 from "refractor/lang/unrealscript.js";
refractor.register(i204);
import i205 from "refractor/lang/v.js";
refractor.register(i205);
import i206 from "refractor/lang/vala.js";
refractor.register(i206);
import i207 from "refractor/lang/velocity.js";
refractor.register(i207);
import i208 from "refractor/lang/verilog.js";
refractor.register(i208);
import i209 from "refractor/lang/vhdl.js";
refractor.register(i209);
import i210 from "refractor/lang/vim.js";
refractor.register(i210);
import i211 from "refractor/lang/visual-basic.js";
refractor.register(i211);
import i212 from "refractor/lang/warpscript.js";
refractor.register(i212);
import i213 from "refractor/lang/wasm.js";
refractor.register(i213);
import i214 from "refractor/lang/wiki.js";
refractor.register(i214);
import i215 from "refractor/lang/wolfram.js";
refractor.register(i215);
import i216 from "refractor/lang/xeora.js";
refractor.register(i216);
import i217 from "refractor/lang/xml-doc.js";
refractor.register(i217);
import i218 from "refractor/lang/xojo.js";
refractor.register(i218);
import i219 from "refractor/lang/xquery.js";
refractor.register(i219);
import i220 from "refractor/lang/yang.js";
refractor.register(i220);
import i221 from "refractor/lang/zig.js";
refractor.register(i221);