// https://github.com/wooorm/refractor/issues/48
// export {refractor} from "refractor/lib/all";
// export {toHtml} from "hast-util-to-html";

import {refractor} from "refractor/lib/core";
import {toHtml} from "hast-util-to-html";

// https://github.com/wooorm/refractor/blob/main/lib/common.js

// .split("\n").map(l => l.split(" ")).map(([_, lang, __, from]) => {
// lang = from.replace(";", "").replace("'", "").replace("'", "").split("/")[2].split(".")[0];
// return `'${lang}': () => import("./prismjs_other"),`
// }).join("\n")

// copy(`import {refractor} from "refractor/lib/core";\n\n` + (value.split("\n\n").map(l => l.split("\n").map(l => l.trim()).map((l, i) => {
// return `import i${i} from ${l.split(" ")[3].replace("import(", "").replace("),", "")};\nrefractor.register(i${i});`;
// })).map(l => l.join("\n"))[0]))

const languages_raw: {[key: string]: () => Promise<{_?: undefined}>} = {
    'clike': () => import("./prismjs_common"),
    'c': () => import("./prismjs_common"),
    'cpp': () => import("./prismjs_common"),
    'arduino': () => import("./prismjs_common"),
    'bash': () => import("./prismjs_common"),
    'csharp': () => import("./prismjs_common"),
    'markup': () => import("./prismjs_common"),
    'css': () => import("./prismjs_common"),
    'diff': () => import("./prismjs_common"),
    'go': () => import("./prismjs_common"),
    'ini': () => import("./prismjs_common"),
    'java': () => import("./prismjs_common"),
    'regex': () => import("./prismjs_common"),
    'javascript': () => import("./prismjs_common"),
    'json': () => import("./prismjs_common"),
    'kotlin': () => import("./prismjs_common"),
    'less': () => import("./prismjs_common"),
    'lua': () => import("./prismjs_common"),
    'makefile': () => import("./prismjs_common"),
    'yaml': () => import("./prismjs_common"),
    'markdown': () => import("./prismjs_common"),
    'objectivec': () => import("./prismjs_common"),
    'perl': () => import("./prismjs_common"),
    'markup-templating': () => import("./prismjs_common"),
    'php': () => import("./prismjs_common"),
    'python': () => import("./prismjs_common"),
    'r': () => import("./prismjs_common"),
    'ruby': () => import("./prismjs_common"),
    'rust': () => import("./prismjs_common"),
    'sass': () => import("./prismjs_common"),
    'scss': () => import("./prismjs_common"),
    'sql': () => import("./prismjs_common"),
    'swift': () => import("./prismjs_common"),
    'typescript': () => import("./prismjs_common"),
    'basic': () => import("./prismjs_common"),
    'vbnet': () => import("./prismjs_common"),

    'abap': () => import("./prismjs_other"),
    'abnf': () => import("./prismjs_other"),
    'actionscript': () => import("./prismjs_other"),
    'ada': () => import("./prismjs_other"),
    'agda': () => import("./prismjs_other"),
    'al': () => import("./prismjs_other"),
    'antlr4': () => import("./prismjs_other"),
    'apacheconf': () => import("./prismjs_other"),
    'apex': () => import("./prismjs_other"),
    'apl': () => import("./prismjs_other"),
    'applescript': () => import("./prismjs_other"),
    'aql': () => import("./prismjs_other"),
    'arff': () => import("./prismjs_other"),
    'asciidoc': () => import("./prismjs_other"),
    'aspnet': () => import("./prismjs_other"),
    'asm6502': () => import("./prismjs_other"),
    'autohotkey': () => import("./prismjs_other"),
    'autoit': () => import("./prismjs_other"),
    'batch': () => import("./prismjs_other"),
    'bbcode': () => import("./prismjs_other"),
    'birb': () => import("./prismjs_other"),
    'bison': () => import("./prismjs_other"),
    'bnf': () => import("./prismjs_other"),
    'brainfuck': () => import("./prismjs_other"),
    'brightscript': () => import("./prismjs_other"),
    'bro': () => import("./prismjs_other"),
    'bsl': () => import("./prismjs_other"),
    'cfscript': () => import("./prismjs_other"),
    'chaiscript': () => import("./prismjs_other"),
    'cil': () => import("./prismjs_other"),
    'clojure': () => import("./prismjs_other"),
    'cmake': () => import("./prismjs_other"),
    'cobol': () => import("./prismjs_other"),
    'coffeescript': () => import("./prismjs_other"),
    'concurnas': () => import("./prismjs_other"),
    'csp': () => import("./prismjs_other"),
    'coq': () => import("./prismjs_other"),
    'crystal': () => import("./prismjs_other"),
    'css-extras': () => import("./prismjs_other"),
    'csv': () => import("./prismjs_other"),
    'cypher': () => import("./prismjs_other"),
    'd': () => import("./prismjs_other"),
    'dart': () => import("./prismjs_other"),
    'dataweave': () => import("./prismjs_other"),
    'dax': () => import("./prismjs_other"),
    'dhall': () => import("./prismjs_other"),
    'django': () => import("./prismjs_other"),
    'dns-zone-file': () => import("./prismjs_other"),
    'docker': () => import("./prismjs_other"),
    'dot': () => import("./prismjs_other"),
    'ebnf': () => import("./prismjs_other"),
    'editorconfig': () => import("./prismjs_other"),
    'eiffel': () => import("./prismjs_other"),
    'ejs': () => import("./prismjs_other"),
    'elixir': () => import("./prismjs_other"),
    'elm': () => import("./prismjs_other"),
    'etlua': () => import("./prismjs_other"),
    'erb': () => import("./prismjs_other"),
    'erlang': () => import("./prismjs_other"),
    'excel-formula': () => import("./prismjs_other"),
    'fsharp': () => import("./prismjs_other"),
    'factor': () => import("./prismjs_other"),
    'false': () => import("./prismjs_other"),
    'firestore-security-rules': () => import("./prismjs_other"),
    'flow': () => import("./prismjs_other"),
    'fortran': () => import("./prismjs_other"),
    'ftl': () => import("./prismjs_other"),
    'gml': () => import("./prismjs_other"),
    'gcode': () => import("./prismjs_other"),
    'gdscript': () => import("./prismjs_other"),
    'gedcom': () => import("./prismjs_other"),
    'gherkin': () => import("./prismjs_other"),
    'git': () => import("./prismjs_other"),
    'glsl': () => import("./prismjs_other"),
    'graphql': () => import("./prismjs_other"),
    'groovy': () => import("./prismjs_other"),
    'textile': () => import("./prismjs_other"),
    'haml': () => import("./prismjs_other"),
    'handlebars': () => import("./prismjs_other"),
    'haskell': () => import("./prismjs_other"),
    'haxe': () => import("./prismjs_other"),
    'hcl': () => import("./prismjs_other"),
    'hlsl': () => import("./prismjs_other"),
    'uri': () => import("./prismjs_other"),
    'http': () => import("./prismjs_other"),
    'hpkp': () => import("./prismjs_other"),
    'hsts': () => import("./prismjs_other"),
    'ichigojam': () => import("./prismjs_other"),
    'icon': () => import("./prismjs_other"),
    'icu-message-format': () => import("./prismjs_other"),
    'idris': () => import("./prismjs_other"),
    'ignore': () => import("./prismjs_other"),
    'inform7': () => import("./prismjs_other"),
    'io': () => import("./prismjs_other"),
    'j': () => import("./prismjs_other"),
    'javadoclike': () => import("./prismjs_other"),
    'scala': () => import("./prismjs_other"),
    'javadoc': () => import("./prismjs_other"),
    'javastacktrace': () => import("./prismjs_other"),
    'jexl': () => import("./prismjs_other"),
    'jolie': () => import("./prismjs_other"),
    'jq': () => import("./prismjs_other"),
    'js-templates': () => import("./prismjs_other"),
    'jsdoc': () => import("./prismjs_other"),
    'n4js': () => import("./prismjs_other"),
    'js-extras': () => import("./prismjs_other"),
    'json5': () => import("./prismjs_other"),
    'jsonp': () => import("./prismjs_other"),
    'jsstacktrace': () => import("./prismjs_other"),
    'julia': () => import("./prismjs_other"),
    'keyman': () => import("./prismjs_other"),
    'kumir': () => import("./prismjs_other"),
    'latex': () => import("./prismjs_other"),
    'latte': () => import("./prismjs_other"),
    'scheme': () => import("./prismjs_other"),
    'lilypond': () => import("./prismjs_other"),
    'liquid': () => import("./prismjs_other"),
    'lisp': () => import("./prismjs_other"),
    'livescript': () => import("./prismjs_other"),
    'llvm': () => import("./prismjs_other"),
    'log': () => import("./prismjs_other"),
    'lolcode': () => import("./prismjs_other"),
    'matlab': () => import("./prismjs_other"),
    'mel': () => import("./prismjs_other"),
    'mizar': () => import("./prismjs_other"),
    'mongodb': () => import("./prismjs_other"),
    'monkey': () => import("./prismjs_other"),
    'moonscript': () => import("./prismjs_other"),
    'n1ql': () => import("./prismjs_other"),
    'nand2tetris-hdl': () => import("./prismjs_other"),
    'naniscript': () => import("./prismjs_other"),
    'nasm': () => import("./prismjs_other"),
    'neon': () => import("./prismjs_other"),
    'nevod': () => import("./prismjs_other"),
    'nginx': () => import("./prismjs_other"),
    'nim': () => import("./prismjs_other"),
    'nix': () => import("./prismjs_other"),
    'nsis': () => import("./prismjs_other"),
    'ocaml': () => import("./prismjs_other"),
    'opencl': () => import("./prismjs_other"),
    'openqasm': () => import("./prismjs_other"),
    'oz': () => import("./prismjs_other"),
    'parigp': () => import("./prismjs_other"),
    'parser': () => import("./prismjs_other"),
    'pascal': () => import("./prismjs_other"),
    'pascaligo': () => import("./prismjs_other"),
    'psl': () => import("./prismjs_other"),
    'pcaxis': () => import("./prismjs_other"),
    'peoplecode': () => import("./prismjs_other"),
    'phpdoc': () => import("./prismjs_other"),
    'php-extras': () => import("./prismjs_other"),
    'plsql': () => import("./prismjs_other"),
    'powerquery': () => import("./prismjs_other"),
    'powershell': () => import("./prismjs_other"),
    'processing': () => import("./prismjs_other"),
    'prolog': () => import("./prismjs_other"),
    'promql': () => import("./prismjs_other"),
    'properties': () => import("./prismjs_other"),
    'protobuf': () => import("./prismjs_other"),
    'stylus': () => import("./prismjs_other"),
    'twig': () => import("./prismjs_other"),
    'pug': () => import("./prismjs_other"),
    'puppet': () => import("./prismjs_other"),
    'pure': () => import("./prismjs_other"),
    'purebasic': () => import("./prismjs_other"),
    'purescript': () => import("./prismjs_other"),
    'qsharp': () => import("./prismjs_other"),
    'q': () => import("./prismjs_other"),
    'qml': () => import("./prismjs_other"),
    'qore': () => import("./prismjs_other"),
    'racket': () => import("./prismjs_other"),
    'jsx': () => import("./prismjs_other"),
    'tsx': () => import("./prismjs_other"),
    'reason': () => import("./prismjs_other"),
    'rego': () => import("./prismjs_other"),
    'renpy': () => import("./prismjs_other"),
    'rest': () => import("./prismjs_other"),
    'rip': () => import("./prismjs_other"),
    'roboconf': () => import("./prismjs_other"),
    'robotframework': () => import("./prismjs_other"),
    'sas': () => import("./prismjs_other"),
    'shell-session': () => import("./prismjs_other"),
    'smali': () => import("./prismjs_other"),
    'smalltalk': () => import("./prismjs_other"),
    'smarty': () => import("./prismjs_other"),
    'sml': () => import("./prismjs_other"),
    'solidity': () => import("./prismjs_other"),
    'solution-file': () => import("./prismjs_other"),
    'soy': () => import("./prismjs_other"),
    'turtle': () => import("./prismjs_other"),
    'sparql': () => import("./prismjs_other"),
    'splunk-spl': () => import("./prismjs_other"),
    'sqf': () => import("./prismjs_other"),
    'squirrel': () => import("./prismjs_other"),
    'stan': () => import("./prismjs_other"),
    'iecst': () => import("./prismjs_other"),
    't4-templating': () => import("./prismjs_other"),
    't4-cs': () => import("./prismjs_other"),
    't4-vb': () => import("./prismjs_other"),
    'tap': () => import("./prismjs_other"),
    'tcl': () => import("./prismjs_other"),
    'tt2': () => import("./prismjs_other"),
    'toml': () => import("./prismjs_other"),
    'typoscript': () => import("./prismjs_other"),
    'unrealscript': () => import("./prismjs_other"),
    'v': () => import("./prismjs_other"),
    'vala': () => import("./prismjs_other"),
    'velocity': () => import("./prismjs_other"),
    'verilog': () => import("./prismjs_other"),
    'vhdl': () => import("./prismjs_other"),
    'vim': () => import("./prismjs_other"),
    'visual-basic': () => import("./prismjs_other"),
    'warpscript': () => import("./prismjs_other"),
    'wasm': () => import("./prismjs_other"),
    'wiki': () => import("./prismjs_other"),
    'wolfram': () => import("./prismjs_other"),
    'xeora': () => import("./prismjs_other"),
    'xml-doc': () => import("./prismjs_other"),
    'xojo': () => import("./prismjs_other"),
    'xquery': () => import("./prismjs_other"),
    'yang': () => import("./prismjs_other"),
    'zig': () => import("./prismjs_other"),
};

export function listLanguages(): string[] {
    return Object.keys(languages_raw);
}
export async function highlight(text: string, language_name: string): Promise<string> {
    if(!refractor.registered(language_name)) {
        if(languages_raw[language_name]) {
            await languages_raw[language_name]!();
        }
    }

    return toHtml(refractor.highlight(text, language_name));
}
